Accept=Onartu
Close=Itxi
Price= Prezioa
SelectOption=Aukeratu

MainGUI.CreateSale= Eskaintza sortu
MainGUI.QuerySales= Eskaintzak konstsultatu
MainGUI.SelectOption=Aukeratu
MainGUI.MainTitle=Merkatua
MainGUI.Login=Saioa hasi
MainGUI.Register=Erregistratu erabiltzailea
MainGUI.close= Saioa itxi
MainGUI.Aceptar= Onartu eskaintzak
MainGUI.Visualizar= Erakutsi onartutako eskaintzak
MainGUI.rese= Crear reseña
Principal.Guest= Jarraitu gonbidatu gisa
PrincipalGUI.Idioma= Hizkuntza

LoginGUI.login= Saioa hasi
LoginGUI.labelPass=Sartu pasahitza
LoginGUI.labelMail=Sartu posta elektronikoa
LoginGUI.FormatoError=Posta elektronikoaren formatu okerra
LoginGUI.UsuarioError=Erabiltzaile-izen edo pasahitz okerra

RegisterGUI.correoLabel=Sartu zure helbide elektronikoa
RegisterGUI.nombreLabel=Sartu zure izena
RegisterGUI.contraseñaLabel=Sartu zure pasahitza
RegisterGUI.seller_t=Eroslea
RegisterGUI.seller_F=Saltzailea
RegisterGUI.registerBt=erregistratu
RegisterGUI.errorLabel=E-posta formatu okerra
RegisterGUI.bienvenida=Ongi etorri
RegisterGUI.registrado= Posta elektronikoa dagoeneko erregistratuta dago

MainGUI.Ofertas=Ikusi Onartutako Eskaintzak
MainGUI.aceptar=Eskaintza onartu
MainGUI.Close=Itxita
CreateSaleGUI.Title=Tituloa
CreateSaleGUI.Description=Deskripzioa
CreateSaleGUI.Status=Egoera
CreateSaleGUI.Category=Kategoria
CreateSaleGUI.Price=Prezioa
CreateSaleGUI.PriceMustBeGreaterThan0=ERROR, prezioa 0 baino handiagoa
CreateSaleGUI.ProductCreated=Eskaintza sortuta
CreateSaleGUI.CreateProduct=Sortu Eskaintza
CreateSaleGUI.ErrorNumber=Error, prezioa zenbaki bat izan behar da
CreateSaleGUI.ErrorQuery=Error, datuak falta dira
CreateSaleGUI.LoadPicture=Argazkia igo
CreateSaleGUI.PublicationDate=Argitarapen eguna

QuerySalesGUI.Search=Bilatu
QuerySalesGUI.NoProducts=Ez daude eskaintzak
QuerySalesGUI.Price=Prezioa
QuerySalesGUI.FindProducts=Eskaintzak bilatu
QuerySalesGUI.Products=Eskaintzak (Double-click eskaintza ikusteko)

ShowSaleGUI.Title=Eskaintza xehestasunak


DataAccess.SaleAlreadyExist=ERROR, Eskaintza existizen da
DataAccess.ErrorSaleMustBeLaterThanToday=ERROR, data gaur baino beranduago izan behar da
DataAccess.ErrorFileNotUploadedException=ERROR, Argazkia igo behar da

AceptarGUI.carrito=Nire eskaerak
AceptarGUI.ofertas=Hautatu erabilgarri dagoen eskaintza bat:
AceptarGUI.aceptada=Eskaintza eskatuta! Eroslearen erantzunaren zain
AceptarGUI.erroraceptar=Errorea eskaintza onartzerakoan
AceptarGUI.mail= Posta

VisualizarGUI.Solicitudes= Eskaerak

CarritoGUI.exit=Irten
CarritoGUI.solicitudLabel=Eskatutako produktuen zerrenda
CarritoGUI.exito=Eskaera ondo baliogabetu da!
CarritoGUI.fracaso=Errorea erosketa-eskaera baliogabetzerakoan
CarritoGUI.cancelar=Baliogabetu eskaera
CarritoGUI.vacio= Ez duzu eskaintzarik erosteko eskaerarik egin

PagoGUI.titular=Sartu txartelaren titularra:
PagoGUI.numero=Sartu txartelaren zenbakia:
PagoGUI.fecha=Iraungitze-data:
PagoGUI.cobro=Ordaindu

# --- VisualizarReseGUI ---
VisualizarReseGUI.reseña=Iritziak
VisualizarReseGUI.vendedor=Saltzailea
VisualizarReseGUI.titulo=Titulua
VisualizarReseGUI.valoracion=Balorazioa
VisualizarReseGUI.descripcion=Deskripzioa
VisualizarReseGUI.ver=Ikusi Iritziak
VisualizarReseGUI.noreseñas=Ez daude iritzi argitaraturik
VisualizarReseGUI.sireseñas=Iritziak aurkituta

BorrarCuentaGUI.texto=Ziur zaude zure kontua ezabatu nahi duzula?
BorrarCuentaGUI.aceptar=Bai, kontua ezabatu
BorrarCuentaGUI.cancelar=Utzi

CambiarContraseñaGUI.labelConfirmation=Berretsi pasahitza
CambiarContraseñaGUI.labelPassword=Pasahitz berria
CambiarContraseñaGUI.cambio=Pasahitza aldatu
CambiarContraseñaGUI.FormatoError=Pasahitzak ez datoz bat
CambiarContraseñaGUI.UsuarioError=Oraingo pasahitza okerra da
CambiarContraseñaGUI.CambioConfirmado=Pasahitza ondo aldatu da!
CambiarContraseñaGUI.actual=Oraingo pasahitza
CambiarContraseñaGUI.NoContraseña=Oraingo pasahitza ez da kontu honena.

ShowReseGUI.correo=Posta
ShowReseGUI.valoracion=Balorazioa

UsuarioGUI.correo=Posta elektronikoa
UsuarioGUI.tipo=Mota:
UsuarioGUI.reseñas=Nire Iritziak
UsuarioGUI.borrar=Kontua Ezabatu
UsuarioGUI.foto=Argazkia Aldatu
UsuarioGUI.titulo=Erabiltzailearen Profila
UsuarioGUI.cambiar=Pasahitza Aldatu
UsuarioGUI.nombre=Izena:
UsuarioGUI.vendedor=SALTZAILEA
UsuarioGUI.comprador=EROSLEA
UsuarioGUI.admin=ADMIN

SolicitudesGUI=Erosketa-eskaerak erakutsi
SolicitudesGUI.borrar=Produktua ezabatu
SolicitudesGUI.lista= Igotako eskaintzen zerrenda
SolicitudesGUI.solicitudes= Eskaeren zerrenda
SolicitudesGUI.aceptar= Onartu

CrearRese.CrerRes=Crear valoración